### ISSUE TITLE
Compatibility with Python 3.12?

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/ParamTools#132]
When trying to run `taxcalc`  (`tc --test` in the command line) on Python 3.12, I ran into the following error, which seems to implicate ParamTools:

```
Traceback (most recent call last):
  File "/Users/jason.debacker/anaconda3/envs/taxcalc-dev/bin/tc", line 6, in <module>
    from taxcalc.cli.tc import cli_tc_main
  File "/Users/jason.debacker/anaconda3/envs/taxcalc-dev/lib/python3.12/site-packages/taxcalc/__init__.py", line 4, in <module>
    from taxcalc.calculator import *
  File "/Users/jason.debacker/anaconda3/envs/taxcalc-dev/lib/python3.12/site-packages/taxcalc/calculator.py", line 13, in <module>
    import paramtools
  File "/Users/jason.debacker/anaconda3/envs/taxcalc-dev/lib/python3.12/site-packages/paramtools/__init__.py", line 1, in <module>
    from paramtools.schema_factory import SchemaFactory
  File "/Users/jason.debacker/anaconda3/envs/taxcalc-dev/lib/python3.12/site-packages/paramtools/schema_factory.py", line 3, in <module>
    from paramtools.schema import (
  File "/Users/jason.debacker/anaconda3/envs/taxcalc-dev/lib/python3.12/site-packages/paramtools/schema.py", line 13, in <module>
    from paramtools.exceptions import UnknownTypeException, ParamToolsError
  File "/Users/jason.debacker/anaconda3/envs/taxcalc-dev/lib/python3.12/site-packages/paramtools/exceptions.py", line 4, in <module>
    from paramtools import utils
  File "/Users/jason.debacker/anaconda3/envs/taxcalc-dev/lib/python3.12/site-packages/paramtools/utils.py", line 7, in <module>
    import fsspec
  File "/Users/jason.debacker/anaconda3/envs/taxcalc-dev/lib/python3.12/site-packages/fsspec/__init__.py", line 43, in <module>
    for spec in entry_points.get("fsspec.specs", []):
                ^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Comment by martinholmer** [comment]
ParamTools 0.18.2 works with Python 3.12, so this issue has been resolved.

**Comment by martinholmer** [comment]
@jdebacker, would you please close ParamTools issue #132.
